#!/bin/ash
# DHCPD Entry File

if [ ! -e /data/dhcpd.conf ]; then
    cp /etc/dhcp/dhcpd.conf.example /data/dhcpd.conf
fi

/usr/sbin/dhcpd -cf /data/dhcpd.conf -t && echo Configuration check successful. || echo Configuration check failed. Startup aborted. && exit 1

/usr/sbin/dhcpd -lf /data/dhcpd.leases -T && echo Lease File check successful. || echo Lease File check failed and may be corrupt. Startup aborted. && exit 1

/usr/sbin/dhcpd -cf /data/dhcpd.conf -lf /data/dhcpd.leases -f -d -q

exit 0
