#!/bin/ash
# DHCPD Entry File

echo $(date) - Starting DHCPd

if [ ! -e /data/dhcpd.conf ]; then
    cp /etc/dhcp/dhcpd.conf.example /data/dhcpd.conf
fi

/usr/sbin/dhcpd -cf /data/dhcpd.conf -t
if [ $? -eq 0 ]; then
    echo Configuration check successful.
else
    echo Configuration check failed. Startup aborted.
    exit 1
fi

if [ -e /data/dhcpd.leases ]; then
    /usr/sbin/dhcpd -cf /data/dhcpd.conf -lf /data/dhcpd.leases -T
    if [ $? -eq 0 ]; then
        echo Lease File check successful.
    else
        echo Lease File check failed and may be corrupt. Startup aborted.
        exit 1
    fi
else
    echo No Existing Lease File.
    touch /data/dhcpd.leases
fi

/usr/sbin/dhcpd -cf /data/dhcpd.conf -lf /data/dhcpd.leases -f -d

exit 0
